// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBudget.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyBudget.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260328211640_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyBudget.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("createDate");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("createdBy");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currencyId");

                    b.Property<Guid?>("HolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("holderId");

                    b.Property<Guid?>("KeeperId")
                        .HasColumnType("uuid")
                        .HasColumnName("keeperId");

                    b.Property<Guid?>("LinkedAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("linkedAccountId");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modifiedBy");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("modifyDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parentId");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("typeId");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("HolderId");

                    b.HasIndex("KeeperId");

                    b.HasIndex("LinkedAccountId");

                    b.HasIndex("ParentId");

                    b.HasIndex("TypeId");

                    b.ToTable("Account", "app");
                });

            modelBuilder.Entity("MyBudget.Domain.AccountType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<bool>("AllowsTransactions")
                        .HasColumnType("boolean")
                        .HasColumnName("allowsTransactions");

                    b.Property<bool>("CalcFullTimeBalance")
                        .HasColumnType("boolean")
                        .HasColumnName("calcFullTimeBalance");

                    b.Property<bool>("CanBeCreatedByUser")
                        .HasColumnType("boolean")
                        .HasColumnName("canBeCreatedByUser");

                    b.Property<bool>("CanBeDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("canBeDeleted");

                    b.Property<bool>("CanBeRenamed")
                        .HasColumnType("boolean")
                        .HasColumnName("canBeRenamed");

                    b.Property<bool>("CanChangeActiveStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("canChangeActiveStatus");

                    b.Property<bool>("CheckAmountBeforeDeactivate")
                        .HasColumnType("boolean")
                        .HasColumnName("checkAmountBeforeDeactivate");

                    b.Property<int?>("Classification")
                        .HasColumnType("integer")
                        .HasColumnName("classification");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("createDate");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("createdBy");

                    b.Property<bool>("HasCurrency")
                        .HasColumnType("boolean")
                        .HasColumnName("hasCurrency");

                    b.Property<bool>("HasHolder")
                        .HasColumnType("boolean")
                        .HasColumnName("hasHolder");

                    b.Property<bool>("HasInitialBalance")
                        .HasColumnType("boolean")
                        .HasColumnName("hasInitialBalance");

                    b.Property<bool>("HasKeeper")
                        .HasColumnType("boolean")
                        .HasColumnName("hasKeeper");

                    b.Property<short>("KeeperGroup")
                        .HasColumnType("smallint")
                        .HasColumnName("keeperGroup");

                    b.Property<Guid?>("LinkedAccountTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("linkedAccountTypeId");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modifiedBy");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("modifyDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.HasKey("Id");

                    b.HasIndex("LinkedAccountTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AccountType", "app");
                });

            modelBuilder.Entity("MyBudget.Domain.AccountTypeAccountTypeLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Guid>("AncestorId")
                        .HasColumnType("uuid")
                        .HasColumnName("ancestorId");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("childId");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("createDate");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("createdBy");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modifiedBy");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("modifyDate");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("AncestorId", "ChildId")
                        .IsUnique();

                    b.ToTable("AccountTypeAccountTypeLink", "app");
                });

            modelBuilder.Entity("MyBudget.Domain.Audit.Generated.AccountAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<bool?>("Active_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("active_MOD");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("createDate");

                    b.Property<bool?>("CreateDate_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("createDate_MOD");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("createdBy");

                    b.Property<bool?>("CreatedBy_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("createdBy_MOD");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currencyId");

                    b.Property<bool?>("CurrencyId_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("currencyId_MOD");

                    b.Property<Guid?>("HolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("holderId");

                    b.Property<bool?>("HolderId_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("holderId_MOD");

                    b.Property<Guid?>("KeeperId")
                        .HasColumnType("uuid")
                        .HasColumnName("keeperId");

                    b.Property<bool?>("KeeperId_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("keeperId_MOD");

                    b.Property<Guid?>("LinkedAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("linkedAccountId");

                    b.Property<bool?>("LinkedAccountId_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("linkedAccountId_MOD");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modifiedBy");

                    b.Property<bool?>("ModifiedBy_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("modifiedBy_MOD");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("modifyDate");

                    b.Property<bool?>("ModifyDate_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("modifyDate_MOD");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<bool?>("Name_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("name_MOD");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parentId");

                    b.Property<bool?>("ParentId_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("parentId_MOD");

                    b.Property<long>("RevId")
                        .HasColumnType("bigint")
                        .HasColumnName("rev");

                    b.Property<int>("RevType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("typeId");

                    b.Property<bool?>("TypeId_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("typeId_MOD");

                    b.HasKey("Id");

                    b.HasIndex("RevId");

                    b.ToTable("AccountAudit", "appAudit");
                });

            modelBuilder.Entity("MyBudget.Domain.Audit.Generated.AccountTypeAccountTypeLinkAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<bool?>("Active_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("active_MOD");

                    b.Property<Guid?>("AncestorId")
                        .HasColumnType("uuid")
                        .HasColumnName("ancestorId");

                    b.Property<bool?>("AncestorId_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("ancestorId_MOD");

                    b.Property<Guid?>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("childId");

                    b.Property<bool?>("ChildId_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("childId_MOD");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("createDate");

                    b.Property<bool?>("CreateDate_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("createDate_MOD");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("createdBy");

                    b.Property<bool?>("CreatedBy_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("createdBy_MOD");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modifiedBy");

                    b.Property<bool?>("ModifiedBy_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("modifiedBy_MOD");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("modifyDate");

                    b.Property<bool?>("ModifyDate_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("modifyDate_MOD");

                    b.Property<long>("RevId")
                        .HasColumnType("bigint")
                        .HasColumnName("rev");

                    b.Property<int>("RevType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RevId");

                    b.ToTable("AccountTypeAccountTypeLinkAudit", "appAudit");
                });

            modelBuilder.Entity("MyBudget.Domain.Audit.Generated.AccountTypeAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<bool?>("Active_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("active_MOD");

                    b.Property<bool?>("AllowsTransactions")
                        .HasColumnType("boolean")
                        .HasColumnName("allowsTransactions");

                    b.Property<bool?>("AllowsTransactions_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("allowsTransactions_MOD");

                    b.Property<bool?>("CalcFullTimeBalance")
                        .HasColumnType("boolean")
                        .HasColumnName("calcFullTimeBalance");

                    b.Property<bool?>("CalcFullTimeBalance_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("calcFullTimeBalance_MOD");

                    b.Property<bool?>("CanBeCreatedByUser")
                        .HasColumnType("boolean")
                        .HasColumnName("canBeCreatedByUser");

                    b.Property<bool?>("CanBeCreatedByUser_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("canBeCreatedByUser_MOD");

                    b.Property<bool?>("CanBeDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("canBeDeleted");

                    b.Property<bool?>("CanBeDeleted_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("canBeDeleted_MOD");

                    b.Property<bool?>("CanBeRenamed")
                        .HasColumnType("boolean")
                        .HasColumnName("canBeRenamed");

                    b.Property<bool?>("CanBeRenamed_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("canBeRenamed_MOD");

                    b.Property<bool?>("CanChangeActiveStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("canChangeActiveStatus");

                    b.Property<bool?>("CanChangeActiveStatus_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("canChangeActiveStatus_MOD");

                    b.Property<bool?>("CheckAmountBeforeDeactivate")
                        .HasColumnType("boolean")
                        .HasColumnName("checkAmountBeforeDeactivate");

                    b.Property<bool?>("CheckAmountBeforeDeactivate_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("checkAmountBeforeDeactivate_MOD");

                    b.Property<int?>("Classification")
                        .HasColumnType("integer")
                        .HasColumnName("classification");

                    b.Property<bool?>("Classification_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("classification_MOD");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("createDate");

                    b.Property<bool?>("CreateDate_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("createDate_MOD");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("createdBy");

                    b.Property<bool?>("CreatedBy_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("createdBy_MOD");

                    b.Property<bool?>("HasCurrency")
                        .HasColumnType("boolean")
                        .HasColumnName("hasCurrency");

                    b.Property<bool?>("HasCurrency_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("hasCurrency_MOD");

                    b.Property<bool?>("HasHolder")
                        .HasColumnType("boolean")
                        .HasColumnName("hasHolder");

                    b.Property<bool?>("HasHolder_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("hasHolder_MOD");

                    b.Property<bool?>("HasInitialBalance")
                        .HasColumnType("boolean")
                        .HasColumnName("hasInitialBalance");

                    b.Property<bool?>("HasInitialBalance_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("hasInitialBalance_MOD");

                    b.Property<bool?>("HasKeeper")
                        .HasColumnType("boolean")
                        .HasColumnName("hasKeeper");

                    b.Property<bool?>("HasKeeper_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("hasKeeper_MOD");

                    b.Property<short?>("KeeperGroup")
                        .HasColumnType("smallint")
                        .HasColumnName("keeperGroup");

                    b.Property<bool?>("KeeperGroup_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("keeperGroup_MOD");

                    b.Property<Guid?>("LinkedAccountTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("linkedAccountTypeId");

                    b.Property<bool?>("LinkedAccountTypeId_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("linkedAccountTypeId_MOD");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modifiedBy");

                    b.Property<bool?>("ModifiedBy_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("modifiedBy_MOD");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("modifyDate");

                    b.Property<bool?>("ModifyDate_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("modifyDate_MOD");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<bool?>("Name_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("name_MOD");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<bool?>("Priority_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("priority_MOD");

                    b.Property<long>("RevId")
                        .HasColumnType("bigint")
                        .HasColumnName("rev");

                    b.Property<int>("RevType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RevId");

                    b.ToTable("AccountTypeAudit", "appAudit");
                });

            modelBuilder.Entity("MyBudget.Domain.Audit.Generated.AuditRevisionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("autor");

                    b.Property<DateTime>("RevisionDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("revisionDate");

                    b.HasKey("Id");

                    b.ToTable("AuditRevisionEntity", "appAudit");
                });

            modelBuilder.Entity("MyBudget.Domain.Audit.Generated.CurrencyAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<bool?>("Active_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("active_MOD");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("code");

                    b.Property<bool?>("Code_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("code_MOD");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("createDate");

                    b.Property<bool?>("CreateDate_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("createDate_MOD");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("createdBy");

                    b.Property<bool?>("CreatedBy_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("createdBy_MOD");

                    b.Property<bool?>("IsAccounting")
                        .HasColumnType("boolean")
                        .HasColumnName("isAccounting");

                    b.Property<bool?>("IsAccounting_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("isAccounting_MOD");

                    b.Property<int?>("Iso4217")
                        .HasColumnType("integer")
                        .HasColumnName("iso4217");

                    b.Property<bool?>("Iso4217_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("iso4217_MOD");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modifiedBy");

                    b.Property<bool?>("ModifiedBy_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("modifiedBy_MOD");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("modifyDate");

                    b.Property<bool?>("ModifyDate_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("modifyDate_MOD");

                    b.Property<long>("RevId")
                        .HasColumnType("bigint")
                        .HasColumnName("rev");

                    b.Property<int>("RevType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RevId");

                    b.ToTable("CurrencyAudit", "appAudit");
                });

            modelBuilder.Entity("MyBudget.Domain.Audit.Generated.HolderAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<bool?>("Active_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("active_MOD");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("createDate");

                    b.Property<bool?>("CreateDate_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("createDate_MOD");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("createdBy");

                    b.Property<bool?>("CreatedBy_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("createdBy_MOD");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modifiedBy");

                    b.Property<bool?>("ModifiedBy_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("modifiedBy_MOD");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("modifyDate");

                    b.Property<bool?>("ModifyDate_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("modifyDate_MOD");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<bool?>("Name_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("name_MOD");

                    b.Property<long>("RevId")
                        .HasColumnType("bigint")
                        .HasColumnName("rev");

                    b.Property<int>("RevType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RevId");

                    b.ToTable("HolderAudit", "appAudit");
                });

            modelBuilder.Entity("MyBudget.Domain.Audit.Generated.KeeperAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<bool?>("Active_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("active_MOD");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("createDate");

                    b.Property<bool?>("CreateDate_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("createDate_MOD");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("createdBy");

                    b.Property<bool?>("CreatedBy_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("createdBy_MOD");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modifiedBy");

                    b.Property<bool?>("ModifiedBy_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("modifiedBy_MOD");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("modifyDate");

                    b.Property<bool?>("ModifyDate_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("modifyDate_MOD");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<bool?>("Name_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("name_MOD");

                    b.Property<long>("RevId")
                        .HasColumnType("bigint")
                        .HasColumnName("rev");

                    b.Property<int>("RevType")
                        .HasColumnType("integer");

                    b.Property<short?>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<bool?>("Type_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("type_MOD");

                    b.HasKey("Id");

                    b.HasIndex("RevId");

                    b.ToTable("KeeperAudit", "appAudit");
                });

            modelBuilder.Entity("MyBudget.Domain.Audit.Generated.TransactionAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<bool?>("Active_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("active_MOD");

                    b.Property<string>("Comment")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("comment");

                    b.Property<bool?>("Comment_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("comment_MOD");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("createDate");

                    b.Property<bool?>("CreateDate_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("createDate_MOD");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("createdBy");

                    b.Property<bool?>("CreatedBy_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("createdBy_MOD");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp")
                        .HasColumnName("date");

                    b.Property<bool?>("Date_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("date_MOD");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modifiedBy");

                    b.Property<bool?>("ModifiedBy_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("modifiedBy_MOD");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("modifyDate");

                    b.Property<bool?>("ModifyDate_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("modifyDate_MOD");

                    b.Property<long>("RevId")
                        .HasColumnType("bigint")
                        .HasColumnName("rev");

                    b.Property<int>("RevType")
                        .HasColumnType("integer");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<bool?>("Status_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("status_MOD");

                    b.Property<short?>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<bool?>("Type_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("type_MOD");

                    b.HasKey("Id");

                    b.HasIndex("RevId");

                    b.ToTable("TransactionAudit", "appAudit");
                });

            modelBuilder.Entity("MyBudget.Domain.Audit.Generated.TransactionItemAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountId");

                    b.Property<bool?>("AccountId_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("accountId_MOD");

                    b.Property<bool?>("Account_MOD")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<bool?>("Active_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("active_MOD");

                    b.Property<double?>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("amount");

                    b.Property<bool?>("Amount_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("amount_MOD");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("createDate");

                    b.Property<bool?>("CreateDate_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("createDate_MOD");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("createdBy");

                    b.Property<bool?>("CreatedBy_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("createdBy_MOD");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modifiedBy");

                    b.Property<bool?>("ModifiedBy_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("modifiedBy_MOD");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("modifyDate");

                    b.Property<bool?>("ModifyDate_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("modifyDate_MOD");

                    b.Property<long>("RevId")
                        .HasColumnType("bigint")
                        .HasColumnName("rev");

                    b.Property<int>("RevType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transactionId");

                    b.Property<bool?>("TransactionId_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("transactionId_MOD");

                    b.Property<short?>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<bool?>("Type_MOD")
                        .HasColumnType("boolean")
                        .HasColumnName("type_MOD");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("RevId");

                    b.ToTable("TransactionItemAudit", "appAudit");
                });

            modelBuilder.Entity("MyBudget.Domain.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("createDate");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("createdBy");

                    b.Property<bool>("IsAccounting")
                        .HasColumnType("boolean")
                        .HasColumnName("isAccounting");

                    b.Property<int>("Iso4217")
                        .HasColumnType("integer")
                        .HasColumnName("iso4217");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modifiedBy");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("modifyDate");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Iso4217")
                        .IsUnique();

                    b.ToTable("Currency", "app");
                });

            modelBuilder.Entity("MyBudget.Domain.Holder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("createDate");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("createdBy");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modifiedBy");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("modifyDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Holder", "app");
                });

            modelBuilder.Entity("MyBudget.Domain.Keeper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("createDate");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("createdBy");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modifiedBy");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("modifyDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Keeper", "app");
                });

            modelBuilder.Entity("MyBudget.Domain.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Comment")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("createDate");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("createdBy");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp")
                        .HasColumnName("date");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modifiedBy");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("modifyDate");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("Transaction", "app");
                });

            modelBuilder.Entity("MyBudget.Domain.TransactionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountId");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("createDate");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("createdBy");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modifiedBy");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("modifyDate");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transactionId");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionItem", "app");
                });

            modelBuilder.Entity("MyBudget.Domain.Account", b =>
                {
                    b.HasOne("MyBudget.Domain.Currency", "Currency")
                        .WithMany("Accounts")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyBudget.Domain.Holder", "Holder")
                        .WithMany("Accounts")
                        .HasForeignKey("HolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyBudget.Domain.Keeper", "Keeper")
                        .WithMany("Accounts")
                        .HasForeignKey("KeeperId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyBudget.Domain.Account", "LinkedAccount")
                        .WithMany()
                        .HasForeignKey("LinkedAccountId");

                    b.HasOne("MyBudget.Domain.Account", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyBudget.Domain.AccountType", "Type")
                        .WithMany("Accounts")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Holder");

                    b.Navigation("Keeper");

                    b.Navigation("LinkedAccount");

                    b.Navigation("Parent");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MyBudget.Domain.AccountType", b =>
                {
                    b.HasOne("MyBudget.Domain.AccountType", "LinkedAccountType")
                        .WithMany()
                        .HasForeignKey("LinkedAccountTypeId");

                    b.Navigation("LinkedAccountType");
                });

            modelBuilder.Entity("MyBudget.Domain.AccountTypeAccountTypeLink", b =>
                {
                    b.HasOne("MyBudget.Domain.AccountType", "Ancestor")
                        .WithMany("AncestorAccountTypeLinks")
                        .HasForeignKey("AncestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyBudget.Domain.AccountType", "Child")
                        .WithMany("ChildAccountTypeLinks")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ancestor");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("MyBudget.Domain.Audit.Generated.AccountAudit", b =>
                {
                    b.HasOne("MyBudget.Domain.Audit.Generated.AuditRevisionEntity", "Rev")
                        .WithMany()
                        .HasForeignKey("RevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rev");
                });

            modelBuilder.Entity("MyBudget.Domain.Audit.Generated.AccountTypeAccountTypeLinkAudit", b =>
                {
                    b.HasOne("MyBudget.Domain.Audit.Generated.AuditRevisionEntity", "Rev")
                        .WithMany()
                        .HasForeignKey("RevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rev");
                });

            modelBuilder.Entity("MyBudget.Domain.Audit.Generated.AccountTypeAudit", b =>
                {
                    b.HasOne("MyBudget.Domain.Audit.Generated.AuditRevisionEntity", "Rev")
                        .WithMany()
                        .HasForeignKey("RevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rev");
                });

            modelBuilder.Entity("MyBudget.Domain.Audit.Generated.CurrencyAudit", b =>
                {
                    b.HasOne("MyBudget.Domain.Audit.Generated.AuditRevisionEntity", "Rev")
                        .WithMany()
                        .HasForeignKey("RevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rev");
                });

            modelBuilder.Entity("MyBudget.Domain.Audit.Generated.HolderAudit", b =>
                {
                    b.HasOne("MyBudget.Domain.Audit.Generated.AuditRevisionEntity", "Rev")
                        .WithMany()
                        .HasForeignKey("RevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rev");
                });

            modelBuilder.Entity("MyBudget.Domain.Audit.Generated.KeeperAudit", b =>
                {
                    b.HasOne("MyBudget.Domain.Audit.Generated.AuditRevisionEntity", "Rev")
                        .WithMany()
                        .HasForeignKey("RevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rev");
                });

            modelBuilder.Entity("MyBudget.Domain.Audit.Generated.TransactionAudit", b =>
                {
                    b.HasOne("MyBudget.Domain.Audit.Generated.AuditRevisionEntity", "Rev")
                        .WithMany()
                        .HasForeignKey("RevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rev");
                });

            modelBuilder.Entity("MyBudget.Domain.Audit.Generated.TransactionItemAudit", b =>
                {
                    b.HasOne("MyBudget.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("MyBudget.Domain.Audit.Generated.AuditRevisionEntity", "Rev")
                        .WithMany()
                        .HasForeignKey("RevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Rev");
                });

            modelBuilder.Entity("MyBudget.Domain.TransactionItem", b =>
                {
                    b.HasOne("MyBudget.Domain.Account", "Account")
                        .WithMany("TransactionItems")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyBudget.Domain.Transaction", "Transaction")
                        .WithMany("TransactionItems")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("MyBudget.Domain.Account", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("TransactionItems");
                });

            modelBuilder.Entity("MyBudget.Domain.AccountType", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("AncestorAccountTypeLinks");

                    b.Navigation("ChildAccountTypeLinks");
                });

            modelBuilder.Entity("MyBudget.Domain.Currency", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("MyBudget.Domain.Holder", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("MyBudget.Domain.Keeper", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("MyBudget.Domain.Transaction", b =>
                {
                    b.Navigation("TransactionItems");
                });
#pragma warning restore 612, 618
        }
    }
}
